import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Wallet, ArrowLeftRight, Plus, Download, Printer } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { useWords, useData, useAction, Page, Panel, Dialog, Field, Button, DataTable, Loading, money, today, dateText, exportCsv } from './ui';

export function AccountSelect({accounts,value,onChange,label}:any) {
  const w=useWords();
  return <Field label={label||w('Bank / cash account','البنك / الخزينة')}><select required value={value||''} onChange={e=>onChange(e.target.value)}><option value="">{w('Choose where the money moves','حدد حساب حركة الأموال')}</option>{accounts.filter((a:any)=>a.active).map((a:any)=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</select></Field>;
}
export function TreasuryPaymentDialog({sourceType,record,onClose}:any) {
  const w=useWords(),q=useData('/treasury'),a=useAction();
  const [form,setForm]=useState({sourceType,sourceId:record.id,accountId:'',date:today(),reference:'',requestKey:crypto.randomUUID()});
  return <Dialog title={w('Pay from treasury','سداد من الخزينة')} onClose={onClose}>{a.feedback}<p className="ops-context-help">{w('Record the actual payment. This will deduct the full amount once and lock this cost record.','سجل السداد الفعلي. سيتم خصم كامل المبلغ مرة واحدة وقفل تعديل هذا السجل.')} <strong>{money(record.amount??record.netSalary??record.bankAmount)}</strong></p>{!q.data?<Loading query={q}/>:<form onSubmit={async e=>{e.preventDefault();try{await a.run('/treasury/record-payments',form);onClose();}catch{}}}><div className="ops-form-grid"><AccountSelect accounts={q.data.accounts} value={form.accountId} onChange={(v:string)=>setForm({...form,accountId:v})}/><Field label={w('Payment date','تاريخ السداد')}><input required type="date" max={today()} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label={w('Receipt / reference','رقم الإيصال / المرجع')}><input required value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></Field></div><div className="ops-form-footer"><Button secondary type="button" onClick={onClose}>{w('Cancel','إلغاء')}</Button><Button disabled={a.busy||!form.accountId}>{w('Confirm actual payment','تأكيد السداد الفعلي')}</Button></div></form>}</Dialog>;
}
const labels:any={OPENING:['Opening balance','رصيد افتتاحي'],RECEIPT:['Client receipt','تحصيل عميل'],SUPPLIER_PAYMENT:['Supplier payment','سداد مورد'],TRANSFER_IN:['Transfer in','تحويل وارد'],TRANSFER_OUT:['Transfer out','تحويل صادر'],ADJUSTMENT_IN:['Adjustment in','تسوية إضافة'],ADJUSTMENT_OUT:['Adjustment out','تسوية خصم'],COST_PAYMENT:['Cost payment','سداد مصروف / راتب / قسط']};
export function Treasury() {
  const w=useWords(), {user}=useAuth(),q=useData('/treasury'),a=useAction();
  const admin=user?.role==='ADMIN',edit=admin||user?.role==='ACCOUNTANT';
  const [tab,setTab]=useState('accounts'),[account,setAccount]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[modal,setModal]=useState(''),[form,setForm]=useState<any>({}),[client,setClient]=useState('');
  const open=(kind:string,extra:any={})=>{a.clear();setForm({name:'',kind:'BANK',bankName:'',reference:'',openingDate:today(),openingBalance:0,accountId:account,date:today(),amount:'',fromAccountId:account,toAccountId:'',direction:'IN',notes:'',requestKey:crypto.randomUUID(),...extra});setModal(kind);};
  if(!q.data)return <Loading query={q}/>;
  const d=q.data,rows=d.entries.filter((e:any)=>(!account||e.accountId===account)&&(!from||dateText(e.date)>=from)&&(!to||dateText(e.date)<=to));
  const selected=d.accounts.find((x:any)=>x.id===account);
  const moveName=(e:any)=>labels[e.kind]?w(labels[e.kind][0],labels[e.kind][1]):e.kind;
  const cols=[{key:'date',label:w('Date','التاريخ'),render:(e:any)=>dateText(e.date)},{key:'account',label:w('Account','الحساب'),render:(e:any)=>e.account.name},{key:'kind',label:w('Movement','الحركة'),render:moveName},{key:'reference',label:w('Reference','المرجع')},{key:'amount',label:w('In / out','وارد / صادر'),render:(e:any)=><strong className={Number(e.amount)<0?'treasury-out':'treasury-in'} dir="ltr">{Number(e.amount)>0?'+':''}{money(e.amount)}</strong>},{key:'balance',label:w('Account balance after movement','رصيد الحساب بعد الحركة'),render:(e:any)=>money(e.balance)},{key:'notes',label:w('Details','التفاصيل')}];
  async function save(e:any){e.preventDefault();try {const path=modal==='allocate'?`/treasury/payments/${form.paymentId}/allocate`:'/treasury/'+({account:'accounts',transfer:'transfers',adjustment:'adjustments'} as any)[modal];await a.run(path,form);setModal('');}catch{}}
  const total=d.accounts.reduce((s:number,x:any)=>s+Number(x.balance),0);
  return <Page title={w('Accounts & treasury','الحسابات والخزينة')} description={w('Your transport company’s banks and cash. Every client has a separate statement. All amounts are EGP.','بنوك وخزائن شركة النقل، وكشف حساب مستقل لكل عميل. كل المبالغ بالجنيه المصري.')} actions={<>{admin&&<Button onClick={()=>open('account')}><Plus size={16}/>{w('Add account','إضافة حساب')}</Button>}{edit&&<Button secondary onClick={()=>open('transfer')}><ArrowLeftRight size={16}/>{w('Transfer','تحويل')}</Button>}{admin&&<Button secondary onClick={()=>open('adjustment')}>{w('Balance adjustment','تسوية رصيد')}</Button>}</>}>
    <div className="home-stats treasury-stats">{[[w('Total cash & banks','إجمالي البنوك والخزائن'),money(total)],[w('Client balances','مستحقات العملاء'),money(d.companies.reduce((s:number,x:any)=>s+Number(x.outstanding),0))],[w('Payments awaiting allocation','مدفوعات بدون حساب'),d.unallocated.length]].map(([l,v])=><div className="home-stat teal" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>
    <div className="ops-context-help">{w('Record client receipts and supplier payments from Billing. Use Expenses & payroll to pay costs. Transfers only move money between your accounts; they do not change a client balance.','سجل تحصيل العملاء وسداد الموردين من الفواتير، وسدد التكاليف من المصروفات والرواتب. التحويل ينقل الأموال بين حساباتك ولا يغير مديونية العميل.')} <Link to="/billing" className="ops-text-link">{w('Open billing','فتح الفواتير')}</Link> · <Link to="/accounting" className="ops-text-link">{w('Open expenses & payroll','فتح المصروفات والرواتب')}</Link></div>
    {!modal&&a.feedback}
    <div className="ops-help-tabs">{[['accounts',w('Accounts & movements','الحسابات والحركات')],['clients',w('Client statements','كشوف العملاء')],['unallocated',w('Historical payments','المدفوعات السابقة')]].map(([v,l])=><Button key={v} secondary={tab!==v} onClick={()=>setTab(v)}>{l}</Button>)}</div>
    {tab==='accounts'&&<>
      {!d.accounts.length?<Panel title={w('Start with your first bank or cash account','ابدأ بإضافة بنك أو خزينة')}><p className="ops-help">{w('The administrator adds the actual opening balance and its date. Do not include historical payments twice: allocate only payments not already included in that opening balance.','يضيف المدير الرصيد الفعلي وتاريخه. تجنب ازدواج المدفوعات السابقة: اربط فقط الحركات غير المحتسبة في الرصيد الافتتاحي.')}</p></Panel>:<div className="treasury-accounts">{d.accounts.map((x:any)=><div className={'treasury-account '+(account===x.id?'selected':'')} key={x.id}><button onClick={()=>setAccount(account===x.id?'':x.id)} aria-pressed={account===x.id}><span><Wallet size={19}/>{x.name}</span><strong>{money(x.balance)}</strong><small>{x.kind==='BANK'?w('Bank','بنك'):w('Cash','نقدي')} · {x.active?w('Active','نشط'):w('Archived','مؤرشف')} · {dateText(x.openingDate)}</small></button>{admin&&<Button secondary disabled={a.busy||x.active&&Number(x.balance)!==0} onClick={async()=>{try{await a.run(`/treasury/accounts/${x.id}/status`,{active:!x.active});}catch{}}}>{x.active?w('Archive empty account','أرشفة الحساب الفارغ'):w('Reactivate','إعادة تفعيل')}</Button>}</div>)}</div>}
      <div className="treasury-filters"><Field label={w('Account','الحساب')}><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">{w('All accounts','كل الحسابات')}</option>{d.accounts.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label={w('From','من')}><input type="date" value={from} max={to||today()} onChange={e=>setFrom(e.target.value)}/></Field><Field label={w('To','إلى')}><input type="date" value={to} min={from} max={today()} onChange={e=>setTo(e.target.value)}/></Field><Button secondary onClick={()=>exportCsv('treasury-movements',rows.map((e:any)=>({...e,account:e.account.name,kind:moveName(e),date:dateText(e.date)})),cols.map(c=>({key:c.key,label:c.label})))}><Download size={16}/>{w('Export movements','تصدير الحركات')}</Button></div>
      {selected&&<p className="ops-help">{w('Opening before filter','الرصيد قبل الفترة')}: <b>{money(from?d.entries.filter((e:any)=>e.accountId===account&&dateText(e.date)<from).reduce((s:number,e:any)=>s+Number(e.amount),0):0)}</b> · {w('Filtered net movement','صافي حركات الفترة')}: <b>{money(rows.reduce((s:number,e:any)=>s+Number(e.amount),0))}</b></p>}
      <DataTable rows={rows} columns={cols}/>
    </>}
    {tab==='clients'&&<><p className="ops-help">{w('Issued invoices only, grouped by invoice recipient. Drafts and void documents are excluded. Treasury allocation does not change the client’s paid amount.','الفواتير المعتمدة حسب جهة السداد. تستبعد المسودات والملغاة. ربط المدفوع بالخزينة لا يغير المبلغ المحصل من العميل.')}</p><DataTable rows={d.companies} columns={[{key:'companyName',label:w('Company','الشركة')},...['billed','paid','outstanding'].map((key,i)=>({key,label:[w('Invoiced','المفوتر'),w('Received','المحصل'),w('Outstanding','المتبقي')][i],render:(x:any)=>money(x[key])}))]} actions={(x:any)=><Button secondary onClick={()=>setClient(x.id)}>{w('Statement','كشف الحساب')}</Button>}/></>}
    {tab==='unallocated'&&<><div className="ops-context-help">{w('These payments already reduced invoice balances but have no bank/cash assignment. Allocation adds a treasury entry only. Start the account before the payment date with an opening balance excluding these movements. If already included, keep them unallocated and reconcile separately.','هذه المدفوعات محسوبة بالفعل في الفواتير لكنها غير مرتبطة بحساب. الربط يضيف حركة خزينة فقط. يجب أن يبدأ الحساب قبل تاريخ الدفع برصيد لا يشمل هذه الحركات. إذا كانت محتسبة بالرصيد الافتتاحي اتركها دون ربط وراجع التسوية.')}</div><DataTable rows={d.unallocated} columns={[{key:'date',label:w('Date','التاريخ'),render:(p:any)=>dateText(p.date)},{key:'document',label:w('Document / company','المستند / الشركة'),render:(p:any)=><>{p.document.number}<small>{p.document.client?.companyName||p.document.partner?.name}</small></>},{key:'reference',label:w('Reference','المرجع')},{key:'amount',label:w('Amount','المبلغ'),render:(p:any)=>money(p.amount)}]} actions={admin?(p:any)=><Button secondary onClick={()=>open('allocate',{paymentId:p.id,amount:p.amount,date:dateText(p.date),document:p.document.number})}>{w('Assign account','تحديد الحساب')}</Button>:undefined}/></>}
    {modal&&<Dialog title={modal==='account'?w('Add bank / cash account','إضافة بنك / خزينة'):modal==='transfer'?w('Transfer between your accounts','تحويل بين حسابات الشركة'):modal==='adjustment'?w('Administrator balance adjustment','تسوية رصيد بواسطة المدير'):w('Allocate historical payment','ربط دفعة سابقة')} onClose={()=>{if(!a.busy)setModal('');}}>{a.feedback}<form onSubmit={save}>
      {modal==='account'?<><p className="ops-help">{w('Opening balances are recorded once and cannot be edited. Use a dated adjustment with a reason for corrections.','يسجل الرصيد الافتتاحي مرة واحدة ولا يعدل. لتصحيح الرصيد استخدم تسوية بتاريخ وسبب واضح.')}</p><div className="ops-form-grid"><Field label={w('Account name','اسم الحساب')}><input required maxLength={250} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label={w('Type','النوع')}><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="BANK">{w('Bank account','حساب بنكي')}</option><option value="CASH">{w('Cash treasury','خزينة نقدية')}</option></select></Field><Field label={w('Bank / branch (optional)','البنك / الفرع (اختياري)')}><input value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value})}/></Field><Field label={w('Account reference (optional)','مرجع الحساب (اختياري)')}><input maxLength={100} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></Field><Field label={w('Opening date','تاريخ البداية')}><input type="date" required max={today()} value={form.openingDate} onChange={e=>setForm({...form,openingDate:e.target.value})}/></Field><Field label={w('Opening balance (EGP)','الرصيد الافتتاحي (جنيه)')}><input type="number" min="0" max="99999999" step="0.01" required value={form.openingBalance} onChange={e=>setForm({...form,openingBalance:e.target.value})}/></Field></div></>:<>
        {modal==='allocate'&&<p className="ops-context-help">{form.document} · {form.date} · {money(form.amount)}<br/>{w('Confirm this movement is not already included in the opening balance.','تأكد أن هذه الحركة ليست محتسبة في الرصيد الافتتاحي.')}</p>}
        <div className="ops-form-grid">{modal==='transfer'?<><AccountSelect label={w('From account','من حساب')} accounts={d.accounts} value={form.fromAccountId} onChange={(v:string)=>setForm({...form,fromAccountId:v})}/><AccountSelect label={w('To account','إلى حساب')} accounts={d.accounts.filter((x:any)=>x.id!==form.fromAccountId)} value={form.toAccountId} onChange={(v:string)=>setForm({...form,toAccountId:v})}/></>:<AccountSelect accounts={d.accounts} value={form.accountId} onChange={(v:string)=>setForm({...form,accountId:v})}/>}
          {modal!=='allocate'&&<><Field label={w('Amount (EGP)','المبلغ (جنيه)')}><input required type="number" min="0.01" max="99999999" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label={w('Date','التاريخ')}><input required type="date" max={today()} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label={w('Reference','المرجع')}><input required maxLength={250} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></Field>{modal==='adjustment'&&<Field label={w('Direction','الاتجاه')}><select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="IN">{w('Add to balance','إضافة إلى الرصيد')}</option><option value="OUT">{w('Deduct from balance','خصم من الرصيد')}</option></select></Field>}<Field label={w('Reason / notes','السبب / الملاحظات')}><textarea required={modal==='adjustment'} minLength={modal==='adjustment'?5:undefined} maxLength={2000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></>}
        </div></>}
      <div className="ops-form-footer"><Button secondary type="button" onClick={()=>setModal('')}>{w('Cancel','إلغاء')}</Button><Button disabled={a.busy}>{w('Confirm & record','تأكيد وتسجيل')}</Button></div></form></Dialog>}
    {client&&<ClientStatement id={client} onClose={()=>setClient('')}/>}
  </Page>;
}
function ClientStatement({id,onClose}:any){
  const w=useWords(),q=useData('/treasury/clients/'+id);
  if(!q.data)return <Dialog title={w('Client statement','كشف حساب العميل')} onClose={onClose}><Loading query={q}/></Dialog>;
  const {client,documents}=q.data,rows=documents.map((d:any)=>({...d,paid:d.payments.reduce((s:number,p:any)=>s+Number(p.amount),0)})).map((d:any)=>({...d,outstanding:Number(d.total)-d.paid}));
  const cols=[{key:'number',label:w('Invoice','الفاتورة')},{key:'period',label:w('Period','الفترة')},{key:'total',label:w('Invoiced','المفوتر'),render:(d:any)=>money(d.total)},{key:'paid',label:w('Received','المحصل'),render:(d:any)=>money(d.paid)},{key:'outstanding',label:w('Outstanding','المتبقي'),render:(d:any)=>money(d.outstanding)}];
  return <Dialog title={client.companyName} onClose={onClose}><div className="ops-print-document"><h2>{w('Client account statement','كشف حساب العميل')}</h2><p>{client.companyName} · {today()} · EGP</p><div className="ops-actions ops-no-print"><Button secondary onClick={()=>window.print()}><Printer size={16}/>{w('Print / PDF','طباعة / PDF')}</Button><Button secondary onClick={()=>exportCsv('client-statement',rows,cols)}><Download size={16}/>{w('Export invoices','تصدير الفواتير')}</Button></div><div className="ops-invoice-totals">{['total','paid','outstanding'].map((k,i)=><span key={k}>{[w('Invoiced','المفوتر'),w('Received','المحصل'),w('Outstanding','المتبقي')][i]}<strong>{money(rows.reduce((s:number,d:any)=>s+Number(d[k]),0))}</strong></span>)}</div><DataTable printAll rows={rows} columns={cols}/><h3>{w('Receipts and receiving accounts','التحصيلات والحسابات المستقبلة')}</h3><DataTable printAll rows={documents.flatMap((d:any)=>d.payments.map((p:any)=>({...p,number:d.number})))} columns={[{key:'date',label:w('Date','التاريخ'),render:(p:any)=>dateText(p.date)},{key:'number',label:w('Invoice','الفاتورة')},{key:'reference',label:w('Reference','المرجع')},{key:'amount',label:w('Receipt','التحصيل'),render:(p:any)=>money(p.amount)},{key:'account',label:w('Received in','تم التحصيل في'),render:(p:any)=>p.treasuryEntry?.account.name||w('Not allocated','غير مرتبط بخزينة')}]}/><p className="ops-help">{w('Issued invoices and receipts only. Historical receivables and customer advances are not imported automatically.','الفواتير المعتمدة والتحصيلات فقط. لا تستورد المديونيات القديمة أو دفعات العملاء المقدمة تلقائياً.')}</p></div></Dialog>;
}
