CREATE TABLE "AppRole" (
 "id" TEXT PRIMARY KEY, "code" TEXT UNIQUE, "name" TEXT NOT NULL UNIQUE,
 "description" TEXT NOT NULL DEFAULT '', "permissions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 "revision" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "users" ADD COLUMN "roleId" TEXT;
ALTER TABLE "users" ADD CONSTRAINT "users_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "AppRole"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
